MeasuresMVC/Controllers/MeasureController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using Infragistics.Web.Mvc;
using MeasuresMVC.Models;
using Microsoft.AspNet.Identity;
using RandREng.MeasureDBEntity;

namespace MeasuresMVC.Controllers
{

	[Authorize]
	public class MeasureController : Controller
	{
		private MeasureEntities db = new MeasureEntities();

		public ActionResult AddMaterial(int? id)
		{
			AddMaterialModel model = new AddMaterialModel();
			model.MeasureId = id.Value;
			model.MaterialTypeList = db.MaterialTypes.ToList().Select(i => new Lookup(i.Id, i.Description)).ToList();
			model.WidthList = db.Widths.ToList();
			return View(model);
		}

		[GridDataSourceAction]
		public ActionResult GetList()
		{
			IQueryable<MeasureCustomerStore> list = null;
			try
			{
				if (User.IsInRole("Store"))
				{
					string userId = User.Identity.GetUserId();
					List<int> stores = db.AspNetUsers.Find(userId).Stores.Select(s => s.Id).ToList();
					list = (from m in db.MeasureCustomerStores
							where m.StoreId != null
								&& stores.Contains(m.StoreId.Value)
								&& m.MeasureId != null
								&& ((m.Status.Value & Status.Completed) != Status.Completed || m.Status == null)
							orderby m.Enterred
							select m);
				}
				else
				{
					list = (from m in db.MeasureCustomerStores
							where m.StoreId != null
								&& m.MeasureId != null
								&& ((m.Status.Value & Status.Completed) != Status.Completed || m.Status == null)
							orderby m.Enterred 
							select m);
				}
			}
			catch (Exception e)
			{
				List<MeasureCustomerStore> temp = new List<MeasureCustomerStore>();
				ViewBag.Message = e.Message;
				list = temp.AsQueryable();

			}
			return View(list);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult AddMaterial(AddMaterialModel model)
		{
			if (ModelState.IsValid)
			{
				Measure m = db.Measures.Find(model.MeasureId);
				if (m != null)
				{
					MeasureMaterial mm = new MeasureMaterial()
					{
						MaterialTypeId = model.MaterialTypeId.Value,
						AltWidthId = model.AltWidthId,
						WidthId = model.WidthId,
						Description = model.Description,
						PatternMatchWidth = model.PatternWidth,
						PatternMatchLength = model.PatternLength
					};
					m.Materials.Add(mm);
					int c = db.SaveChanges();
					return RedirectToAction("Details/" + model.MeasureId.ToString());
				}
			}
			return View(model);
		}
		public ActionResult DeleteMaterial(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			MeasureMaterial mm = db.MeasureMaterials.Find(id);
			if (mm == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			mm.Deleted = true;
			db.SaveChanges();
			return RedirectToAction("Details/" + mm.MeasureId.ToString());
		}

		public ActionResult UndeleteMaterial(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			MeasureMaterial mm = db.MeasureMaterials.Find(id);
			if (mm == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			mm.Deleted = false;
			db.SaveChanges();
			return RedirectToAction("Details/" + mm.MeasureId.ToString());

		}

		public ActionResult EditMaterial(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			EditMaterialModel model = new EditMaterialModel();

			MeasureMaterial mm = db.MeasureMaterials.Find(id);
			model.MeasureMaterialId = id.Value;
			model.AltWidthId = mm.AltWidthId;
			model.Description = mm.Description;
			model.MaterialTypeId = mm.MaterialTypeId;
			model.PatternLength = mm.PatternMatchLength;
			model.PatternWidth = mm.PatternMatchWidth;
			model.WidthId = mm.WidthId;
			model.MaterialTypeList = db.MaterialTypes.ToList().Select(i => new Lookup(i.Id, i.Description)).ToList();
			model.WidthList = db.Widths.ToList();
			model.MeasureId = mm.MeasureId;
			return View(model);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult EditMaterial(EditMaterialModel model)
		{
			if (ModelState.IsValid)
			{
				MeasureMaterial mm = db.MeasureMaterials.Find(model.MeasureMaterialId);
				if (mm != null)
				{
					mm.MaterialTypeId = model.MaterialTypeId.Value;
					mm.AltWidthId = model.AltWidthId;
					mm.WidthId = model.WidthId;
					mm.Description = model.Description;
					mm.PatternMatchWidth = model.PatternWidth;
					mm.PatternMatchLength = model.PatternLength;
					int c = db.SaveChanges();
					return RedirectToAction("Details/" + mm.MeasureId.ToString());
				}
			}
			model.MaterialTypeList = db.MaterialTypes.ToList().Select(i => new Lookup(i.Id, i.Description)).ToList();
			model.WidthList = db.Widths.ToList();
			return View(model);
		}

		// GET: /Measure/
		public ActionResult Index()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Details(MeasureModel model)
		{
			if (ModelState.IsValid)
			{
				Measure m = (from measure in db.Measures
								 .Include(ma => ma.Materials.Select(r => r.Rooms))
								 .Include(ma => ma.Materials.Select(mt => mt.MaterialType))
								 .Include(s => s.Store)
							 where measure.Id == model.MeasureId select measure).FirstOrDefault();
				if (m == null)
				{
					return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
				}
				List<Room> Rooms = db.Rooms.ToList();

				foreach (MeasureMaterial mm in m.Materials)
				{
					var rooms = new HashSet<int> (mm.Rooms.Select(c => c.RoomId));
					var newRooms = new HashSet<int>(model.Rooms.Where(z => z.MaterialId == mm.Id).Select(z => z.RoomId));

					foreach (var room in Rooms)
					{
						if (newRooms.Contains(room.Id))
						{
							RoomModel rm = model.Rooms.First(r => r.RoomId == room.Id);
							if (!rooms.Contains(room.Id))
							{
								mm.Rooms.Add(new MeasureRoom() { RoomId = room.Id, IncludeCloset = rm.IncludeCloset });
							}
							else
							{
								MeasureRoom mmr = mm.Rooms.First(r => r.RoomId == room.Id);
								mmr.IncludeCloset = rm.IncludeCloset;
							}
						}
						else
						{
							if (rooms.Contains(room.Id))
							{
								MeasureRoom mr = mm.Rooms.FirstOrDefault(z => z.RoomId == room.Id);
//								mm.Rooms.Remove(mr);
								db.MeasureRooms.Remove(mr);
							}
						}
					}
				}
				int change = db.SaveChanges();
				return RedirectToAction("Details", "Customer", new { id = model.CustomerId });
			}
			model = new MeasureModel();
			model.measure = db.Measures.Find(model.MeasureId);
			model.customer = db.Customers.Find(model.measure.CustomerId);
			model.CustomerId = model.customer.Id;
			model.MeasureId = model.measure.Id;

			ViewBag.MaterialList = InsertEmptyFirst(new SelectList(model.measure.Materials, "Id", "Description", null));
			return View(model);
		}
		// GET: /Measure/Details/5
		public ActionResult Details(int? id, string ReturnUrl)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			MeasureModel model = new MeasureModel();
			model.measure = (from measure in db.Measures
							 .Include(ma => ma.Materials.Select(r => r.Rooms))
							 .Include(ma => ma.Materials.Select(mt => mt.MaterialType))
							 .Include(s => s.Store)
						 where measure.Id == id.Value
						 select measure).FirstOrDefault();
			if (model.measure == null)
			{
				return HttpNotFound();
			}
			model.customer = db.Customers.Find(model.measure.CustomerId);
			if (model.customer == null)
			{
				return HttpNotFound();
			}
			model.CustomerId = model.customer.Id;
			model.MeasureId = model.measure.Id;

			model.Rooms = new List<RoomModel>();
			foreach (Room r in db.Rooms.OrderBy(r => r.Name))
			{
				RoomModel room = new RoomModel();
				room.RoomId = r.Id;
				room.Name = r.Name;
				room.ShowCloset = r.ShowCloset;
				foreach (MeasureMaterial mm in model.measure.Materials)
				{
					MeasureRoom mr = mm.Rooms.FirstOrDefault(mr2 => mr2.RoomId == r.Id);
					if (mr != null)
					{
//						room.Name = mr.Name;
						room.MaterialId = mr.MaterialId;
						room.IncludeCloset = mr.IncludeCloset;
						break;
					}
				}

				model.Rooms.Add(room);
			}
			ViewBag.ReturnUrl = ReturnUrl;
			ViewBag.ShowDeleted = true;

			ViewBag.MaterialList = InsertEmptyFirst(new SelectList(model.measure.Materials, "Id", "Description", null));
			return View(model);
		}

		public IEnumerable<SelectListItem> InsertEmptyFirst(IEnumerable<SelectListItem> list)
		{
			return new[] { new SelectListItem { Text = string.Empty, Value = "-1" } }.Concat(list);
		}

		// GET: /Measure/Create
		public ActionResult Create(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			Measure model = new Measure();
			model.CustomerId = id.Value;
			List<Lookup> stores;
			if (User.IsInRole("Store"))
			{
				stores = db.AspNetUsers.Find(User.Identity.GetUserId()).Stores.OrderBy(s => s.Number).Where(s => s.Active).Select(i => new Lookup(i.Id, i.Number + " - " + i.NickName)).ToList();
			}
			else
			{
				stores = db.Stores.OrderBy(s => s.Number).Where(s => s.Active).ToList().Select(i => new Lookup(i.Id, i.Number + " - " + i.NickName)).ToList();
			}
			if (stores.Count == 1)
			{
				model.StoreId = stores[0].id;
			}
			ViewBag.StoreList = stores;
			return View(model);
		}

		// POST: /Measure/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]

MeasuresMVC/Views/Measure/AddMaterial.cshtml
@using Infragistics.Web.Mvc;
@using MeasuresMVC.Utils;

@model MeasuresMVC.Models.AddMaterialModel

@{
	ViewBag.Title = "Add Materials";
}

<h2>Edit</h2>

@(Html.Infragistics().Loader()
		.ScriptPath(Url.Content("~/Infragistics/js/"))
		.CssPath(Url.Content("~/Infragistics/css/"))
		.Render()
)


@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>Branch</h4>
		<hr />
		@Html.ValidationSummary(true)
		@Html.HiddenFor(model => model.MeasureId)

		<div class="form-group">
			@Html.LabelFor(model => model.MaterialTypeId, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@(Html.Infragistics().ComboFor(model => model.MaterialTypeId)
					.ID("igMaterial")
					.DataSource(Model.MaterialTypeList)
					.ValueKey("id")
					.ValueKeyType(ComboDataType.Number)
					.TextKey("text")
					.DataBind()
					.Render())
				@Html.ValidationMessageFor(model => model.MaterialTypeId)
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Description)
				@Html.ValidationMessageFor(model => model.Description)
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.WidthId, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@(Html.Infragistics().ComboFor(model => model.WidthId)
					.ID("igWidth")
					.DataSource(Model.WidthList)
					.ValueKey("Id")
					.TextKeyType(ComboDataType.Number)
					.TextKey("Value")
					.CascadingSettings(
						settings => settings.ParentComboID("#igMaterial")
						.ParentComboKey("MaterialTypeId")
					)
					.DataBind()
					.Render())
				@Html.ValidationMessageFor(model => model.WidthId)
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.AltWidthId, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@(Html.Infragistics().ComboFor(model => model.AltWidthId)
					.ID("igAltWidth")
					.DataSource(Model.WidthList)
					.ValueKey("Id")
					.TextKeyType(ComboDataType.Number)
					.TextKey("Value")
					.CascadingSettings(
						settings => settings.ParentComboID("#igMaterial")
						.ParentComboKey("MaterialTypeId")
					)
					.DataBind()
					.Render())
				@Html.ValidationMessageFor(model => model.WidthId)
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.PatternWidth, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.PatternWidth)
				@Html.ValidationMessageFor(model => model.PatternWidth)
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.PatternLength, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.PatternLength)
				@Html.ValidationMessageFor(model => model.PatternLength)
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Save" class="btn btn-default" />
			</div>
		</div>
	</div>
}

<div>
	@Html.ActionLink("Back to Measure", "Details", new { id = Model.MeasureId })
</div>
@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

MeasuresMVC/Views/Measure/Create.cshtml
@using Infragistics.Web.Mvc;
@using MeasuresMVC.Utils;
@using RandREng.MeasureDBEntity

@model RandREng.MeasureDBEntity.Measure

@{
    ViewBag.Title = "Create";
}

<h2>Create a New Measure</h2>
@(Html.Infragistics().Loader()
		.ScriptPath(Url.Content("~/Infragistics/js/"))
		.CssPath(Url.Content("~/Infragistics/css/"))
		.Resources("igCombo")
		.Render()
)




@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true)
		@Html.HiddenFor(model => model.CustomerId)

		<div class="form-group">
			@Html.LabelFor(model => model.StoreId, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@(Html.Infragistics().ComboFor(model => model.StoreId)
					.ID("igMaterial")
					.Width("300px")
					.DataSource(ViewBag.StoreList)
					.ValueKey("id")
					.ValueKeyType(ComboDataType.Number)
					.TextKey("text")
					.DataBind()
					.Render()
					)
				@Html.ValidationMessageFor(model => model.StoreId)
			</div>
		</div>

        <div class="form-group">
            @Html.LabelFor(model => model.SpecialInstructions, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.SpecialInstructions, 10, 200, new { style = "width: 650px" })
                @Html.ValidationMessageFor(model => model.SpecialInstructions)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MeasuresMVC/Views/Measure/Delete.cshtml
@using MeasuresMVC.Utils;

@model RandREng.MeasureDBEntity.Measure

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Measure</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Enterred)
        </dt>

        <dd>
            @Html.DisplayFor2(model => model.Enterred)
        </dd>

    </dl>
    @using (Html.BeginForm("Delete", "Measure", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
	{
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
	}
</div>

MeasuresMVC/Views/Measure/Details.cshtml
@using MeasuresMVC.Utils;

@model MeasuresMVC.Models.MeasureModel

@{
	ViewBag.Title = "Details";
}

<div>
	<h2>Measure Details</h2>
	<hr />
	<dl class="dl-horizontal">
		@Html.Partial("~/Views/Customer/_PartialCustomerMin.cshtml", Model.customer)
	</dl>
	<p>
		@Html.ActionLink("Edit Customer", "Edit", new { id = Model.CustomerId }) |
		@Html.ActionLink("Back to Customer", "Details", "Customer", new { id = Model.customer.Id }, null) |
		@Html.ActionLink("Back to List", "Index", "Customer", null, null)
	</p>

	@using (Html.BeginForm("Details", "Measure", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
	{
		@Html.AntiForgeryToken()

		<div class="form-horizontal">

			<hr />
			@Html.ValidationSummary(true)
			@Html.HiddenFor(model => model.MeasureId)
			@Html.HiddenFor(m => m.CustomerId)

			<div class="form-group">
				@Html.LabelFor(model => model.measure.Store, new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.DisplayFor2(model => model.measure.Store.NickName)
				</div>
			</div>

			<div class="form-group">
				@Html.LabelFor(model => model.measure.SpecialInstructions, new { @class = "control-label col-md-2" })
				<div class="col-md-10">
					@Html.TextAreaFor(model => model.measure.SpecialInstructions, 10, 200, new { style = "width: 650px" })
					@Html.ValidationMessageFor(model => model.measure.SpecialInstructions)
				</div>
			</div>

			@*<div class="form-group">
					<div class="col-md-offset-2 col-md-10">
						<input type="submit" value="Save" class="btn btn-default" />
					</div>
				</div>*@
		</div>


		@*</div>*@
		<div>
			<h4>Material List</h4>

			@Html.ActionLink("Add Material", "AddMaterial", new { id = Model.measure.Id })
			<table class="table">
				<tr>
					<th>
						Description
					</th>
					<th>
						Type
					</th>
					<th>
						Width
					</th>
					<th>
						Alt. Width
					</th>
					<th>
						Pattern Width
					</th>
					<th>
						Pattern Length
					</th>
				</tr>
				@foreach (var item in Model.measure.Materials)
				{
					if (!item.Deleted || ViewBag.ShowDeleted)
					{
						<tr>
							<td>
								@Html.DisplayFor(ddd => item.Description)
							</td>
							<td>
								@Html.DisplayFor(ddd => item.MaterialType.Description)
							</td>
							<td>
								@Html.DisplayFor(ddd => item.Width.Value)
							</td>
							<td>
								@Html.DisplayFor(ddd => item.AltWidth.Value)
							</td>
							<td>
								@Html.DisplayFor(ddd => item.PatternMatchWidth)
							</td>
							<td>
								@Html.DisplayFor(ddd => item.PatternMatchLength)
							</td>
							<td>
								@Html.ActionLink("Edit", "EditMaterial", new { id = item.Id }) |
								@if (item.Deleted)
								{
									@Html.ActionLink("Undelete", "UndeleteMaterial", new { id = item.Id })
								}
								else
								{
									@Html.ActionLink("Delete", "DeleteMaterial", new { id = item.Id })
								}
							</td>
						</tr>
					}
				}
			</table>
		</div>
		<hr />
		if (Model.measure.Materials.Count() > 0)
		{
			@*using (Html.BeginForm("Details", "Measure", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
				{
					@Html.AntiForgeryToken()
					@Html.HiddenFor(m => m.MeasureId)
					@Html.HiddenFor(m => m.CustomerId)*@

			<div>
				<h4>Room Assignment</h4>
				<table class="table">
					@Html.EditorFor(model => model.Rooms)
				</table>
			</div>
		}
		<p>
			<div class="form-group">
				<div class="col-md-4">
					<input type="submit" value="Save" class="btn btn-default" /> |
					@Html.ActionLink("Back to Customer", "Details", "Customer", new { id = Model.customer.Id }, null)
				</div>
			</div>
		</p>
	}
</div>

MeasuresMVC/Views/Measure/Edit.cshtml
@model RandREng.MeasureDBEntity.Measure

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Measure</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Enterred, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Enterred)
                @Html.ValidationMessageFor(model => model.Enterred)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MeasuresMVC/Views/Measure/EditMaterial.cshtml
@using Infragistics.Web.Mvc;
@using MeasuresMVC.Utils;

@model MeasuresMVC.Models.EditMaterialModel

@{
	ViewBag.Title = "Edit Materials";
}

<h2>Edit</h2>

@(Html.Infragistics().Loader()
		.ScriptPath(Url.Content("~/Infragistics/js/"))
		.CssPath(Url.Content("~/Infragistics/css/"))
		.Render()
)


@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>Branch</h4>
		<hr />
		@Html.ValidationSummary(true)
		@Html.HiddenFor(model => model.MeasureMaterialId)

		<div class="form-group">
			@Html.LabelFor(model => model.MaterialTypeId, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@(Html.Infragistics().ComboFor(model => model.MaterialTypeId)
					.ID("igMaterial")
					.DataSource(Model.MaterialTypeList)
					.ValueKey("id")
					.ValueKeyType(ComboDataType.Number)
					.TextKey("text")
					.DataBind()
					.Render())
				@Html.ValidationMessageFor(model => model.MaterialTypeId)
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.Description)
				@Html.ValidationMessageFor(model => model.Description)
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.WidthId, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@(Html.Infragistics().ComboFor(model => model.WidthId)
					.ID("igWidth")
					.DataSource(Model.WidthList)
					.ValueKey("Id")
					.TextKeyType(ComboDataType.Number)
					.TextKey("Value")
					.CascadingSettings(
						settings => settings.ParentComboID("#igMaterial")
						.ParentComboKey("MaterialTypeId")
					)
					.DataBind()
					.Render())
				@Html.ValidationMessageFor(model => model.WidthId)
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.AltWidthId, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@(Html.Infragistics().ComboFor(model => model.AltWidthId)
					.ID("igAltWidth")
					.DataSource(Model.WidthList)
					.ValueKey("Id")
					.TextKeyType(ComboDataType.Number)
					.TextKey("Value")
					.CascadingSettings(
						settings => settings.ParentComboID("#igMaterial")
						.ParentComboKey("MaterialTypeId")
					)
					.DataBind()
					.Render())
				@Html.ValidationMessageFor(model => model.WidthId)
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.PatternWidth, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.PatternWidth)
				@Html.ValidationMessageFor(model => model.PatternWidth)
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.PatternLength, new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.PatternLength)
				@Html.ValidationMessageFor(model => model.PatternLength)
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Save" class="btn btn-default" />
			</div>
		</div>
	</div>
}

<div>
	@Html.ActionLink("Back to Measure", "Details", new { id = Model.MeasureId})
</div>
@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}